services:
    nginx:
        container_name: portfolio-nginx
        depends_on:
            - frontend
        image: nginx:1.25.4
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - ./docker/nginx/prod/nginx.conf:/etc/nginx/nginx.conf
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot

    frontend:
        container_name: portfolio-frontend
        build:
            context: ./docker
            dockerfile: Dockerfile
        command: sh -c "npm install && npx nuxi build && node .output/server/index.mjs"
        restart: on-failure
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        command: certonly --webroot -w /var/www/certbot --force-renewal --email iwaniukmaciej1@gmail.com -d maciekiwaniuk.pl --agree-tos
