services:
    portfolio-frontend-build:
        container_name: portfolio-frontend-build
        build:
            context: .
            dockerfile: docker/frontend/build/Dockerfile
        ports:
            - '3000:3000'
        restart: on-failure
        working_dir: /var/www/html
        stdin_open: true
        tty: true

networks:
    default:
        name: portfolio_network_build
