services:
    frontend:
        image: maciekiwaniuk/portfolio-frontend:latest

    nginx:
        image: maciekiwaniuk/portfolio-nginx:latest
        ports:
            - '80:80'
        restart: on-failure
        depends_on:
           - frontend
