services:
    nginx:
        container_name: portfolio-nginx
        depends_on:
            - frontend
        image: nginx:1.27.2-alpine
        ports:
            - 80:80
        restart: unless-stopped
        volumes:
            - ./docker/nginx/prod/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - portfolio-network

    frontend:
        container_name: portfolio-frontend
        image: node:23-alpine
        environment:
            - HOST=0.0.0.0
            - PORT=3000
        command: sh -c "npm install && npx nuxi build && node .output/server/index.mjs"
        restart: on-failure
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - portfolio-network

networks:
    portfolio-network:
        driver: bridge
