services:
    portfolio:
        container_name: portfolio
        image: node:24-alpine
        ports:
            - '3000:3000'
        command: sh -c "npm ci --ignore-scripts=false --foreground-scripts --verbose sharp && npx nuxi dev"
        restart: on-failure
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        stdin_open: true
        tty: true

networks:
    default:
        name: portfolio_network
