services:
    nginx:
        container_name: nginx
        depends_on:
            - frontend
        image: nginx:1.25.4
        platform: linux/amd64
        ports:
            - '80:80'
            - '443:443'
        restart: always
        volumes:
            - .:/var/www/html/frontend
            - ./docker/nginx/dev/nginx.conf:/etc/nginx/nginx.conf
        working_dir: /var/www/html

    frontend:
        build:
            context: ./docker
            dockerfile: Dockerfile
        command: sh -c "npm install && npx nuxi dev"
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - .:/var/www/html/frontend
        working_dir: /var/www/html/frontend
