services:
    nginx:
        container_name: portfolio-nginx
        depends_on:
            - frontend
        image: nginx:1.25.4
        platform: linux/amd64
        ports:
            - '80:80'
            - '443:443'
        restart: always
        volumes:
            - .:/var/www/html/frontend
            - ./docker/nginx/prod/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/ssl/cert.pem:/etc/nginx/ssl/cert.pem
            - ./etc/nginx/ssl/key.pem:/etc/nginx/ssl/key.pem
        working_dir: /var/www/html

    frontend:
        container_name: portfolio-frontend
        build:
            context: ./docker
            dockerfile: Dockerfile
        command: sh -c "npm install && npx nuxi build && node .output/server/index.mjs"
        restart: always
        stdin_open: true
        tty: true
        volumes:
            - .:/var/www/html/frontend
        working_dir: /var/www/html/frontend
