export type TechnologyType =
    'php' |
    'laravel' |
    'javascript' |
    'jquery' |
    'sass' |
    'less' |
    'bootstrap' |
    'mysql' |
    'postgresql' |
    'git' |
    'github' |
    'python' |
    'csharp' |
    'vue' |
    'redis' |
    'pygame' |
    'pyqt5' |
    'pwa' |
    'css' |
    'java' |
    'symfony' |
    'docker' |
    'phpunit' |
    'typescript' |
    'microservices' |
    'rabbitmq' |
    'tailwind' |
    'c' |
    'linux' |
    'nuxt';
